package com.example.springboot_garage.model;

import javax.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.util.List;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Garage {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String location;
    
    @OneToMany(mappedBy = "garage", cascade = CascadeType.ALL)
    private List<Stock> stocks;
    
    @OneToMany(cascade = CascadeType.ALL)
    @JoinColumn(name = "garage_id")
    private List<Service> services;
    
    @OneToMany(cascade = CascadeType.ALL)
    @JoinColumn(name = "garage_id")
    private List<Employe> employes;

    // Constructors, getters, and setters will be generated by Lombok
}